"""init

Revision ID: 062bf198b680
Revises: 
Create Date: 2026-01-28 23:46:43.898153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062bf198b680'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email пользователя (уникальный)'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Имя пользователя (опционально)'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Хэш пароля (если используется локальная аутентификация)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли пользователь'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтвержден ли email'),
    sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Настройки пользователя в формате JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользователи системы ActivityWatch Sync'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='Уникальный UUID устройства'),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('WINDOWS', 'LINUX', 'MACOS', 'ANDROID', 'IOS', 'OTHER', name='deviceplatform', native_enum=False), nullable=False),
    sa.Column('platform_version', sa.String(length=100), nullable=True),
    sa.Column('platform_name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('system', sa.String(length=255), nullable=True),
    sa.Column('client_version', sa.String(length=50), nullable=True, comment='Версия клиентского ПО'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('meta_data', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device'),
    comment='Устройства пользователей для синхронизации'
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор токена'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='ID устройства'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='Хэш токена (никогда не храним сам токен!)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Название токена (например, 'Основной токен')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('user_id', 'device_id', 'name', name='uq_token_name'),
    comment='API токены для аутентификации устройств'
    )
    op.create_index(op.f('ix_api_tokens_device_id'), 'api_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_index('ix_tokens_token_hash', 'api_tokens', ['token_hash'], unique=False)
    op.create_table('sync_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор сессии'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='ID устройства'),
    sa.Column('token_id', sa.Integer(), nullable=True, comment='ID использованного токена'),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Время начала синхронизации'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Время окончания синхронизации'),
    sa.Column('events_count', sa.Integer(), nullable=False, comment='Количество обработанных событий'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'PARTIAL_FAILURE', 'FAILED', name='syncstatus', native_enum=False), nullable=False, comment='Статус синхронизации'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке (если есть)'),
    sa.Column('meta_data', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Дополнительная информация о сессии'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Сессии синхронизации данных'
    )
    op.create_index(op.f('ix_sync_sessions_device_id'), 'sync_sessions', ['device_id'], unique=False)
    op.create_index('ix_sync_sessions_device_time', 'sync_sessions', ['device_id', 'start_time'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор события'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='ID устройства'),
    sa.Column('sync_session_id', sa.Integer(), nullable=True, comment='ID сессии синхронизации'),
    sa.Column('event_id', sa.String(length=255), nullable=False, comment='Уникальный ID события из ActivityWatch'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Время события'),
    sa.Column('duration_seconds', sa.Float(), nullable=False, comment='Длительность события в секундах'),
    sa.Column('app', sa.String(length=255), nullable=False, comment='Название приложения'),
    sa.Column('window_title', sa.Text(), nullable=True, comment='Заголовок окна'),
    sa.Column('url', sa.Text(), nullable=True, comment='URL (для браузеров)'),
    sa.Column('data', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Полные данные события в формате JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Время создания записи в БД'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'event_id', 'timestamp', name='uq_event_unique'),
    comment='События активности пользователей'
    )
    op.create_index(op.f('ix_activity_events_device_id'), 'activity_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_activity_events_timestamp'), 'activity_events', ['timestamp'], unique=False)
    op.create_index('ix_events_app', 'activity_events', ['app'], unique=False)
    op.create_index('ix_events_device_time', 'activity_events', ['device_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_device_time', table_name='activity_events')
    op.drop_index('ix_events_app', table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_timestamp'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_device_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_sync_sessions_device_time', table_name='sync_sessions')
    op.drop_index(op.f('ix_sync_sessions_device_id'), table_name='sync_sessions')
    op.drop_table('sync_sessions')
    op.drop_index('ix_tokens_token_hash', table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_device_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
