"""сделал device_id в таблице devices nullable=True

Revision ID: 6622e70b7477
Revises: 9c2e99ce0968
Create Date: 2026-01-28 13:36:01.502416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6622e70b7477'
down_revision: Union[str, Sequence[str], None] = '9c2e99ce0968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='ID устройства')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='ID устройства')
    # ### end Alembic commands ###
